In [18]:
import pandas as pd
Gold = pd.read_csv('/Users/enricoconte/Desktop/università/specialistica/1 Anno/1 Semestre/DataMan_DataViz/Progetto/Dati/Gold.csv')
del Gold['Unnamed: 0']
Gold

           Date        Close Symbol      Rate  Confirmed
0    2020-01-02  1524.500000   GC=F  0.000000        0.0
1    2020-01-03  1549.199951   GC=F  1.620200        0.0
2    2020-01-05  1571.599976   GC=F  1.445909        0.0
3    2020-01-06  1566.199951   GC=F -0.343600        0.0
4    2020-01-07  1571.800049   GC=F  0.357560        0.0
..          ...          ...    ...       ...        ...
118  2020-05-28  1713.300049   GC=F  0.175408  5819719.0
119  2020-05-29  1736.900024   GC=F  1.377457  5940890.0
120  2020-05-31  1755.199951   GC=F  1.053597  6186277.0
121  2020-06-01  1737.800049   GC=F -0.991334  6281486.0
122  2020-06-02  1725.199951   GC=F -0.725060  6402323.0

[123 rows x 5 columns]

In [20]:
# Normalizzazione e calcolo rendimento cumulato

Gold['daily_rend'] = 0
i=0
for i in range (len(Gold.Close)-1):
     Gold.daily_rend.loc[i+1]=(((Gold['Close'].loc[i+1]*100)/1524.500000)-100)
        
Gold

/Users/enricoconte/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)

           Date        Close Symbol      Rate  Confirmed  daily_rend
0    2020-01-02  1524.500000   GC=F  0.000000        0.0    0.000000
1    2020-01-03  1549.199951   GC=F  1.620200        0.0    1.620200
2    2020-01-05  1571.599976   GC=F  1.445909        0.0    3.089536
3    2020-01-06  1566.199951   GC=F -0.343600        0.0    2.735320
4    2020-01-07  1571.800049   GC=F  0.357560        0.0    3.102660
..          ...          ...    ...       ...        ...         ...
118  2020-05-28  1713.300049   GC=F  0.175408  5819719.0   12.384392
119  2020-05-29  1736.900024   GC=F  1.377457  5940890.0   13.932438
120  2020-05-31  1755.199951   GC=F  1.053597  6186277.0   15.132827
121  2020-06-01  1737.800049   GC=F -0.991334  6281486.0   13.991476
122  2020-06-02  1725.199951   GC=F -0.725060  6402323.0   13.164969

[123 rows x 6 columns]

In [21]:
Silver = pd.read_csv('/Users/enricoconte/Desktop/università/specialistica/1 Anno/1 Semestre/DataMan_DataViz/Progetto/Dati/Silver.csv')
del Silver['Unnamed: 0']
Silver

           Date      Close Symbol      Rate  Confirmed
0    2020-01-02  17.966000   SI=F  0.000000        0.0
1    2020-01-03  18.068001   SI=F  0.567746        0.0
2    2020-01-05  18.215000   SI=F  0.813590        0.0
3    2020-01-06  18.097000   SI=F -0.647818        0.0
4    2020-01-07  18.316000   SI=F  1.210145        0.0
..          ...        ...    ...       ...        ...
121  2020-05-28  17.895000   SI=F  1.181724  5819719.0
122  2020-05-29  18.440001   SI=F  3.045544  5940890.0
123  2020-05-31  18.684999   SI=F  1.328628  6186277.0
124  2020-06-01  18.768000   SI=F  0.444208  6281486.0
125  2020-06-02  18.207001   SI=F -2.989125  6402323.0

[126 rows x 5 columns]

In [27]:
# Normalizzazione e calcolo rendimento cumulato

Silver['daily_rend'] = 0
i=0
for i in range (len(Silver.Close)-1):
     Silver.daily_rend.loc[i+1]=(((Silver['Close'].loc[i+1]*100)/17.966000)-100)
        

#del Silver['Confirmed']
Silver

           Date      Close Symbol      Rate  daily_rend
0    2020-01-02  17.966000   SI=F  0.000000    0.000000
1    2020-01-03  18.068001   SI=F  0.567746    0.567743
2    2020-01-05  18.215000   SI=F  0.813590    1.385952
3    2020-01-06  18.097000   SI=F -0.647818    0.729156
4    2020-01-07  18.316000   SI=F  1.210145    1.948124
..          ...        ...    ...       ...         ...
121  2020-05-28  17.895000   SI=F  1.181724   -0.395188
122  2020-05-29  18.440001   SI=F  3.045544    2.638320
123  2020-05-31  18.684999   SI=F  1.328628    4.002001
124  2020-06-01  18.768000   SI=F  0.444208    4.463986
125  2020-06-02  18.207001   SI=F -2.989125    1.341427

[126 rows x 5 columns]

In [32]:
# JOIN Datasets

gold_silver = pd.merge(Gold, Silver, on= 'Date', how= 'left', suffixes= ('_Gold', '_Silver'))
gold_silver
#gold_silver.isnull().values.any()
#del gold_silver['Rate_Gold']
#del gold_silver['Rate_Silver']
#del gold_silver['Symbol_Gold']
#del gold_silver['Symbol_Silver']
gold_silver

,Date,Close_Gold,Confirmed,daily_rend_Gold,Close_Silver,daily_rend_Silver
0,2020-01-02,1524.500000,0.0,0.000000,17.966000,0.000000
1,2020-01-03,1549.199951,0.0,1.620200,18.068001,0.567743
2,2020-01-05,1571.599976,0.0,3.089536,18.215000,1.385952
3,2020-01-06,1566.199951,0.0,2.735320,18.097000,0.729156
4,2020-01-07,1571.800049,0.0,3.102660,18.316000,1.948124
...,...,...,...,...,...,...
118,2020-05-28,1713.300049,5819719.0,12.384392,17.895000,-0.395188
119,2020-05-29,1736.900024,5940890.0,13.932438,18.440001,2.638320
120,2020-05-31,1755.199951,6186277.0,15.132827,18.684999,4.002001
121,2020-06-01,1737.800049,6281486.0,13.991476,18.768000,4.463986
122,2020-06-02,1725.199951,6402323.0,13.164969,18.207001,1.341427

In [35]:
# Variazione giornaliera cumulativa

gold_silver['Daily_confirmed']=0
i=0
for i in range (len(gold_silver.Confirmed)-1):
    gold_silver.Daily_confirmed.loc[i]=((gold_silver['Confirmed'].loc[i+1]-gold_silver['Confirmed'].loc[i]))
gold_silver

/Users/enricoconte/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)

,Date,Close_Gold,Confirmed,daily_rend_Gold,Close_Silver,daily_rend_Silver,Daily_confirmed
0,2020-01-02,1524.500000,0.0,0.000000,17.966000,0.000000,0.0
1,2020-01-03,1549.199951,0.0,1.620200,18.068001,0.567743,0.0
2,2020-01-05,1571.599976,0.0,3.089536,18.215000,1.385952,0.0
3,2020-01-06,1566.199951,0.0,2.735320,18.097000,0.729156,0.0
4,2020-01-07,1571.800049,0.0,3.102660,18.316000,1.948124,0.0
...,...,...,...,...,...,...,...
118,2020-05-28,1713.300049,5819719.0,12.384392,17.895000,-0.395188,121171.0
119,2020-05-29,1736.900024,5940890.0,13.932438,18.440001,2.638320,245387.0
120,2020-05-31,1755.199951,6186277.0,15.132827,18.684999,4.002001,95209.0
121,2020-06-01,1737.800049,6281486.0,13.991476,18.768000,4.463986,120837.0
122,2020-06-02,1725.199951,6402323.0,13.164969,18.207001,1.341427,0.0

In [39]:
gold_silver['Rate_Confirmed'] = 0
i = 0
for i in range (len(gold_silver.Confirmed)-1):
     gold_silver.Rate_Confirmed.loc[i+1]=((gold_silver['Confirmed'].loc[i+1]-gold_silver['Confirmed'].loc[i])/gold_silver['Confirmed'].loc[i])*100
        
gold_silver

/Users/enricoconte/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in double_scalars
  after removing the cwd from sys.path.
/Users/enricoconte/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)
/Users/enricoconte/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in double_scalars
  after removing the cwd from sys.path.

,Date,Close_Gold,Confirmed,daily_rend_Gold,Close_Silver,daily_rend_Silver,Daily_confirmed,Rate_Confirmed
0,2020-01-02,1524.500000,0.0,0.000000,17.966000,0.000000,0.0,0.000000
1,2020-01-03,1549.199951,0.0,1.620200,18.068001,0.567743,0.0,NaN
2,2020-01-05,1571.599976,0.0,3.089536,18.215000,1.385952,0.0,NaN
3,2020-01-06,1566.199951,0.0,2.735320,18.097000,0.729156,0.0,NaN
4,2020-01-07,1571.800049,0.0,3.102660,18.316000,1.948124,0.0,NaN
...,...,...,...,...,...,...,...,...
118,2020-05-28,1713.300049,5819719.0,12.384392,17.895000,-0.395188,121171.0,2.093079
119,2020-05-29,1736.900024,5940890.0,13.932438,18.440001,2.638320,245387.0,2.082076
120,2020-05-31,1755.199951,6186277.0,15.132827,18.684999,4.002001,95209.0,4.130475
121,2020-06-01,1737.800049,6281486.0,13.991476,18.768000,4.463986,120837.0,1.539036
122,2020-06-02,1725.199951,6402323.0,13.164969,18.207001,1.341427,0.0,1.923701

In [42]:
gold_silver2 = gold_silver[gold_silver['Date'] > '2020-01-23']
gold_silver2.reset_index()
gold_silver2

,Date,Close_Gold,Confirmed,daily_rend_Gold,Close_Silver,daily_rend_Silver,Daily_confirmed,Rate_Confirmed
18,2020-01-24,1571.099976,941.0,3.056738,18.056999,0.506508,1177.0,43.883792
19,2020-01-26,1581.900024,2118.0,3.765171,18.215000,1.385952,809.0,125.079702
20,2020-01-27,1576.800049,2927.0,3.430636,18.000000,0.189246,2651.0,38.196412
21,2020-01-28,1569.199951,5578.0,2.932106,17.402000,-3.139261,588.0,90.570550
22,2020-01-29,1569.800049,6166.0,2.971469,17.431000,-2.977848,2068.0,10.541413
...,...,...,...,...,...,...,...,...
118,2020-05-28,1713.300049,5819719.0,12.384392,17.895000,-0.395188,121171.0,2.093079
119,2020-05-29,1736.900024,5940890.0,13.932438,18.440001,2.638320,245387.0,2.082076
120,2020-05-31,1755.199951,6186277.0,15.132827,18.684999,4.002001,95209.0,4.130475
121,2020-06-01,1737.800049,6281486.0,13.991476,18.768000,4.463986,120837.0,1.539036
122,2020-06-02,1725.199951,6402323.0,13.164969,18.207001,1.341427,0.0,1.923701

In [43]:
# Salvataggio Data Frame in CSV
gold_silver2.to_csv('/Users/enricoconte/Desktop/università/specialistica/1 Anno/1 Semestre/DataMan_DataViz/Progetto/Dati/gold_silver3.csv')

In [44]:
#TEST PRODUCER
from time import sleep
from json import dumps
from kafka import KafkaProducer
from kafka import KafkaConsumer
from pymongo import MongoClient
from json import loads
import requests
import ast
import pymongo
import pandas as pd
import datetime
import time
import io
import json

#SENDING DATA TO PRODUCER
producer = KafkaProducer(bootstrap_servers=['localhost:9092'],
                         value_serializer=lambda x: 
                         dumps(x).encode('utf-8'))


consumer = KafkaConsumer(
    'alphavantage',
     bootstrap_servers=['localhost:9092'],
     auto_offset_reset='earliest',
     enable_auto_commit=True,
     group_id='my-group',
     value_deserializer= lambda x: loads(x.decode('utf-8')))


#import dei dati su mongo
from pymongo import MongoClient
import pymongo
client = MongoClient()
db = client.dataman
alphavantage = db.alphavantage
records_ = gold_silver2.to_dict(orient = 'records')
result = db.alphavantage.insert_many(records_ )
print('Data Correctly sent to MongoDB')

Data Correctly sent to MongoDB